RealtyDemo/Controllers/RealtyListingModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RealtyDemo.Models;

namespace RealtyDemo.Controllers
{
    public class RealtyListingModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RealtyListingModels
        public ActionResult Index()
        {
            return View(db.RealtyListingModels.ToList());
        }

        //GET: RealtyListingModel/Search?searchBy=&searchPhrase=
        public ActionResult Search(string searchBy, string searchPhrase)
        {
            IEnumerable<RealtyListingModel> results;

            if (searchBy == "All" && searchPhrase != null)
                results = RealtyListingHelper.SearchAllAttributes(db.RealtyListingModels, searchPhrase);
            else if (searchBy != "" && searchPhrase != null)
                results = RealtyListingHelper.SearchSpecificAttribute(db.RealtyListingModels, searchBy, searchPhrase);
            else
                return RedirectToAction("Index");

            if (results.ToList().Count == 0)
            {
                ViewBag.Message = "No Results Found";
                return View();
            }
            else
            {
                ViewBag.Message = "Search Results:";
                return View(results);
            }
        }        

        // GET: RealtyListingModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RealtyListingModel realtyListingModel = db.RealtyListingModels.Find(id);
            if (realtyListingModel == null)
            {
                return HttpNotFound();
            }
            return View(realtyListingModel);
        }

        // GET: RealtyListingModels/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: RealtyListingModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MLSID,StreetAddressLine1,StreetAddressLine2,StreetAddressCity,StreetAddressState,StreetAddressZipCode,StreetAddressNeighborhood,SalePrice,InitialListingDate,BedroomCount,Pictures,GarageSizeSquareFeet,HouseSizeSquareFeet,LotSizeSquareFeet,Description")] RealtyListingModel realtyListingModel)
        {
            if (ModelState.IsValid)
            {
                db.RealtyListingModels.Add(realtyListingModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(realtyListingModel);
        }

        // GET: RealtyListingModels/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RealtyListingModel realtyListingModel = db.RealtyListingModels.Find(id);
            if (realtyListingModel == null)
            {
                return HttpNotFound();
            }
            return View(realtyListingModel);
        }

        // POST: RealtyListingModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MLSID,StreetAddressLine1,StreetAddressLine2,StreetAddressCity,StreetAddressState,StreetAddressZipCode,StreetAddressNeighborhood,SalePrice,InitialListingDate,BedroomCount,Pictures,GarageSizeSquareFeet,HouseSizeSquareFeet,LotSizeSquareFeet,Description")] RealtyListingModel realtyListingModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(realtyListingModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(realtyListingModel);
        }

        // GET: RealtyListingModels/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RealtyListingModel realtyListingModel = db.RealtyListingModels.Find(id);
            if (realtyListingModel == null)
            {
                return HttpNotFound();
            }
            return View(realtyListingModel);
        }

        // POST: RealtyListingModels/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RealtyListingModel realtyListingModel = db.RealtyListingModels.Find(id);
            db.RealtyListingModels.Remove(realtyListingModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RealtyDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - West Coast Realty</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="header-wrapper">
        <div id="masthead" class="header-main nav-dark">
            <div class="header-inner flex-row container logo-left medium-logo-center" role="navigation">
                <div>
                    <ul class="nav navbar-nav navbar-center">
                        <li class="nav-top-link">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="nav-top-link">@Html.ActionLink("Listings", "Index", "RealtyListingModels")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")

                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - West Coast Realty</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RealtyDemo/Views/Shared/_SearchPartial.cshtml
@using (Html.BeginForm("Search", "RealtyListingModels", FormMethod.Get, new { @class = "search" }))
{
    <div>
        <table class="table">
            <tr>
                <th>Search Fields</th>
                <th>Search Value</th>
                <th></th>
            </tr>
            <tr>
                <td>
                    <label>@Html.RadioButton("searchBy", "All", true) All</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "MLSID") MLSID</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "StreetAddressCity") City</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "StreetAddressState") State</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "StreetAddressZipCode") Zip Code</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "BedroomCount") Bedrooms</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "BathroomCount") Bathrooms</label>
                    <br />
                    <label>@Html.RadioButton("searchBy", "HouseSizeSquareFeet") Square Feet</label>
                    <br />
                </td>
                <td>
                    <input name="searchPhrase" value="" style="color:black;"/>
                </td>
                <td>
                    <input type="submit" value="Submit" style="color:black;"/>
                </td>
            </tr>
        </table>
    </div>
}